var express = require('express');
var router = express.Router();
var home = require('x-root-path');
var request = require('superagent');
var menuUrls = require(home+'/configs/entry_urls');
module.exports = function(router) {
/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', 
    { title: 'Express',
    menuMsg:menuUrls});
});
router.get('/getBaseInfo', function(req, res, next) {
  res.render('test', { title: 'Express' });
});
router.get('/lodash/methods', function(req, res, next) {
     request
        .get("http://www.imooc.com/course/AjaxCourseMembers")
        .query({ids:9})
        .set('Content-Type', 'application/json')
        .end(function(err, res){
          console.log(res.body);
        });
  res.render('lodash_method', { title: 'Express' });
});
router.get('/lodash/test', function(req, res, next) {
    
  res.render('test', { title: 'Express' });
});
//获得折线图数据
router.get('/lodash/getChartData', function(req, res, next) {
  var results = 

    {
  "data": {
    "thead": [
      "ord_amt_dayweek",
      "ord_amt_dayday",
      "ord_amt"
    ],
    "tbody": [
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160329",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": -0.004588667880823727,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 540075.2,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.09333309517055247,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160327",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": -0.019340334327359574,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 737372.84,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.013430602080231639,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160328",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": -0.264191979324869,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 542564.8499,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.02343843809575494,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160325",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": -0.014164375042109925,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 632975.46,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.034885021288066885,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160326",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": 0.18790565751158828,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 751915.13,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.028907068715588968,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160323",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": 0.07002099917501439,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 637380.5,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.1700376462961237,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "license_code": -1,
        "second_tag_id": 131,
        "dt": "20160324",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": "15",
        "ord_amt_dayday": 0.007357426215580774,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "北京菜",
        "ord_amt": 642069.98,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "地方菜",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.04515240160178801,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160323",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": 0.05920330089378447,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 9.2445742269E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.36266527634086787,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160324",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": -0.005642903260834315,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 9.19240798885E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.09118698987559341,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160325",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": -0.017460680286894063,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 9.03190229189E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.05743065616656797,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160326",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": 0.11596308143307318,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 1.007926951286E8,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.0488818787477559,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160327",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": -0.015356205803656655,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 9.92449017587E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.023029600309458668,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160328",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": -0.16697208185353807,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 8.26737738987E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.015031271038033924,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160329",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": -1,
        "ord_amt_dayday": 0.03478804673080517,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 8.55498330085E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "全部",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.019807042601882787,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160328",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": -0.11371876900216459,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 4.93617784189E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.019616735131007035,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160329",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": 0.025579501791543016,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 5.06244281184E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": -0.024741031216322353,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160326",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": 0.0760844413515976,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 5.6092039399E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.05043030083655983,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160327",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": -0.007071410571801511,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 5.56953895586E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.019062123465545307,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160324",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": -0.009845113993920887,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 5.43630093988E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.08628607378358115,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160325",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": -0.04114842030708803,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 5.21260574389E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.05200933566431026,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      },
      {
        "second_tag_id": -1,
        "license_code": -1,
        "dt": "20160323",
        "aor_type": -1,
        "aor_type_name": "全部",
        "special_flag": -1,
        "first_tag_id": 10,
        "ord_amt_dayday": 0.057694334271514595,
        "wmcity_id": -1,
        "brand_ka_name": "全部",
        "cp_id": -1,
        "special_flag_name": "全部",
        "second_tag_id_name": "全部",
        "ord_amt": 5.49035410188E7,
        "logistics_code": "-1",
        "license_code_name": "全部",
        "aor_id": -1,
        "dist_id_name": "全国",
        "first_tag_id_name": "快餐小吃",
        "dist_id": -1,
        "brand_ka": -1,
        "aor_id_name": "全部",
        "logistics_code_name": "全部",
        "intelligent_flag_name": "全部",
        "wmcity_id_name": "全部",
        "food_flag": -1,
        "ord_amt_dayweek": 0.3774803753633105,
        "intelligent_flag": -1,
        "unit_name": "全国",
        "cp_id_name": "全部",
        "food_flag_name": "全部"
      }
    ]
  },
  "auth": true
};
var fun =req.query.callback;
  res.send(fun+'('+JSON.stringify(results)+')');
});
}
